### ISSUE TITLE
allow custom ordering of sticky posts

### ISSUE THREAD

**Issue by bribroder** [equitablegrowth/equitablegrowth.org#12]
currently sticky posts can't be ordered, and reports cannot be stickied

**Comment by bribroder** [comment]
need to customize the sticky posts per landing page as well

**Comment by sethrubenstein** [comment]
On research page have a featured slot on top of the page, maybe its sticky maybe its not.

Also have the same thing for equitablog page... except make it more than one post then have the rest of the most recent posts fall under that. 

On the homepage pull featured post from research and analysis page
also on data resource center
and equitablog.

**Comment by sethrubenstein** [comment]
Also provide alternate image slot.
