### ISSUE TITLE
Make bylines linkable to person archive page

### ISSUE THREAD

**Issue by sethrubenstein** [equitablegrowth/equitablegrowth.org#14]
Currently the byline links are turned off lets enable them again when the bio page is fixed.

**Comment by sethrubenstein** [comment]
@devansart Once we push #4 and #6 you can go through the person records and click "Is linked" to re-enable the byline link.

**Comment by devansart** [comment]
Can we make the author's name #5bc0a1when it becomes a link to their bio page?
