### ISSUE TITLE
Selection Share Tool Should Be On All Posts

### ISSUE THREAD

**Issue by sethrubenstein** [equitablegrowth/equitablegrowth.org#15]
Enable on all content types... is it even turned on currently?
Share image tools is that currently on?

**Comment by sethrubenstein** [comment]
Looks like the plugins are missing here...

**Comment by sethrubenstein** [comment]
Still tons of javascript bugs from PGM that are blocking the content sharing...

**Comment by sethrubenstein** [comment]
Okay so I fixed the selection sharer problem by killing the minified version of their javascript and replacing $ with WP standard safe jQuery.

**Comment by devansart** [comment]
This looks like it works across the site. Thanks!
