### ISSUE TITLE
Twitter picking up poster's name

### ISSUE THREAD

**Issue by devansart** [equitablegrowth/equitablegrowth.org#19]
Tweet's on tweet deck are picking up the poster's name and not the author's name. So for example, it looks like Bridget wrote this piece (http://equitablegrowth.org/untangling-the-sources-of-racial-wealth-inequality-in-the-united-states/) when it was actually authored by Nick. Bridget was only the person posting it.  You can try tweeting it and looking at it in Tweet deck to see how it gets displayed. 

Screen shot:
![screen shot 2015-10-06 at 10 28 35 am](https://cloud.githubusercontent.com/assets/14931609/10311512/085bd914-6c15-11e5-8ecb-a11176b15204.png)

**Comment by sethrubenstein** [comment]
Ok @devansart I see the problem here. Should be a quick fix that we can include in tonights release.

**Comment by devansart** [comment]
Great. Thanks!

**Comment by devansart** [comment]
I tweeted a story and looked at it in tweet deck and I'm still getting the poster's name and not the author's in the byline.

**Comment by sethrubenstein** [comment]
Post a link to that story in the issue so we can check it.

On Wed, Oct 7, 2015 at 9:44 AM Dave <notifications@github.com> wrote:

> I tweeted a story and looked at it in tweet deck and I'm still getting the
> poster's name and not the author's in the byline.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/equitablegrowth/equitablegrowth.org/issues/19#issuecomment-146200122>
> .
>
-- 

----

Sent from my mobile

Seth Rubenstein

**Comment by sethrubenstein** [comment]
I just checked this article http://equitablegrowth.org/what-happened-to-the-job-ladder-in-the-21st-century/ for example and it correctly has MARSHALL STEINBAUM's twitter in the Twitter meta space.

However on Twitter.com it shows as Bridget Ansel as the author. I think this is something config wise you guys must have done or maybe that she setup related to your domain. Because that page I just posted literally has nothing on the source code with her name so whatever is happening there is definetly happening on Twitters end.

**Comment by devansart** [comment]
http://equitablegrowth.org/what-happened-to-the-job-ladder-in-the-21st-century/ And here is a screen cap of how it looks in tweet deck
![screen shot 2015-10-07 at 9 54 18 am](https://cloud.githubusercontent.com/assets/14931609/10339466/70c099d0-6cd9-11e5-8040-98b341eb567e.png)

**Comment by devansart** [comment]
The author should be Marshall and Austin... or just Marshall.

**Comment by sethrubenstein** [comment]
@devansart see my comment here - https://github.com/equitablegrowth/equitablegrowth.org/issues/19#issuecomment-146202403 whatever is happening in Tweetdeck is on Twitter's end. If you go to view source on that article you wont see a single mention of Bridget or @bridgetansel. So its not happening on the code side.

**Comment by sethrubenstein** [comment]
@devansart Also on the multiple authors bit. Twitter only supports 1 author not 2. So code wise what we're doing is putting the first author in the byline's twitter handle in the meta of the page for Twitter.

**Comment by devansart** [comment]
So are you saying that Twitter just assumes that since she is tweeting it she is the author and we can't really di anything about it?

**Comment by sethrubenstein** [comment]
@devansart No I'm saying that theres something on Twitters end, maybe its config, maybe its caching on their end thats setting her as the author for some reason. Or it could be just Tweetdeck. Officially the byline on a twitter card doesnt appear on links in the official Twitter web and mobile clients.

**Comment by sethrubenstein** [comment]
Let me try talking with dev support at Twitter to figure out why Tweetdeck specifically is showing this. We'll get back to you.

**Comment by devansart** [comment]
Ok. Thanks. I understand the multiple author's thing also.

**Comment by sethrubenstein** [comment]
We'll be doing a push either tonight or tomorrow thatll force code on the site to make Twitter look for the right type of the card.
