### ISSUE TITLE
byline and post date style

### ISSUE THREAD

**Issue by devansart** [equitablegrowth/equitablegrowth.org#22]
We want to tweak the styling of the byline and post date. Attached is a mock up for styling of both the story page and in the feed entries.

**Story page:**
![screen shot 2015-10-07 at 11 10 59 am](https://cloud.githubusercontent.com/assets/14931609/10342171/ce5c1e14-6ce5-11e5-8ebc-8e02c3cf6154.png)

**Feed entry:**
![screen shot 2015-10-07 at 10 47 21 am](https://cloud.githubusercontent.com/assets/14931609/10342581/af1a8476-6ce7-11e5-8ac7-46757df4f0d7.png)

Green is 5bc0a1
Gray is a2a2a2

I can give you a new twitter bird png if you would prefer.

**Comment by sethrubenstein** [comment]
Easy tweak. On the Twitter bird we prefer to keep that as an icon font for
the official Twitter icon. Just tell us what icon you want it and well
change it to that.

On Wed, Oct 7, 2015 at 11:38 AM Dave <notifications@github.com> wrote:

> We want to tweak the styling of the byline and post date. Attached is a
> mock up for styling of both the story page and in the feed entries.
>
> *Story page:*
> [image: screen shot 2015-10-07 at 11 10 59 am]
> <https://cloud.githubusercontent.com/assets/14931609/10342171/ce5c1e14-6ce5-11e5-8ebc-8e02c3cf6154.png>
>
> *Feed entry:*
> [image: screen shot 2015-10-07 at 10 47 21 am]
> <https://cloud.githubusercontent.com/assets/14931609/10342581/af1a8476-6ce7-11e5-8ac7-46757df4f0d7.png>
>
> Green is 5bc0a1
> Gray is a2a2a2
>
> I can give you a new twitter bird png if you would prefer.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/equitablegrowth/equitablegrowth.org/issues/22>.
>
-- 

----

Sent from my mobile

Seth Rubenstein

**Comment by devansart** [comment]
There is a stray twitter bird at the bottom left of this page.  http://equitablegrowth.org/what-happened-to-the-job-ladder-in-the-21st-century/ It would work well in the bylines. (Want me to put different ticket in to omit the stray bird?)
