### ISSUE TITLE
Downloadable Hi-res bio pics

### ISSUE THREAD

**Issue by devansart** [equitablegrowth/equitablegrowth.org#28]
When you roll over the pic on a staff member's bio page you are suppose to get a "download a hi-res photo". The following link shows you what happens when we upload a hi-res image to the person page http://equitablegrowth.org/person/david-evans/ 

And this is the behavior when we just don't upload a hi-res image: http://equitablegrowth.org/person/nbunker/ (A favorable reaction but without the hi-res functionality none the less.)

**Comment by sethrubenstein** [comment]
@devansart Thanks for the well described ticket. This looks to be an easy enough fix. Expect it to go out same time as the Reports page fix tomorrow evening.

**Comment by devansart** [comment]
@sethrubenstein Sounds good, thanks!
