### ISSUE TITLE
Report post type integration

### ISSUE THREAD

**Issue by bribroder** [equitablegrowth/equitablegrowth.org#3]
The header in particular is messed up on reports

**Comment by devansart** [comment]
This is more than a style clean up. The report tool needs to be integrating into the backend so that when we publish a report it goes into the R&A section(http://equitablegrowth.org/research-analysis/) as well as the R&A part of the homepage (top of equitablegrowth.org).

**Comment by sethrubenstein** [comment]
Currently menu z-index is below image.

**Comment by sethrubenstein** [comment]
All thats left to figure out here is fixing the Research and Analysis page template so it includes report post types.
