### ISSUE TITLE
Bridget Ansel's Equitablog value added posts not going to her bio page

### ISSUE THREAD

**Issue by devansart** [equitablegrowth/equitablegrowth.org#30]
Bridget's bio page is not picking up her value added columns within Equitablog.

These are some recent examples:
http://equitablegrowth.org/caring-elderly-america-now-includes-minimum-wage-overtime/

http://equitablegrowth.org/netflix-paid-family-leave-debate/

http://equitablegrowth.org/nevadas-new-school-choice-program-hurt-low-middle-income-students/

http://equitablegrowth.org/reforms-just-time-scheduling-practices-now-congress/

**Comment by devansart** [comment]
Is it possible this is related to issue #8?

**Comment by sethrubenstein** [comment]
Ah so all other posts are showing up just not Equitablog posts?

**Comment by devansart** [comment]
Well, not exactly. The one that shows up is in fact a value added Equitablog post:
http://equitablegrowth.org/bypass-u-s-estate-taxes/
But it does not have the value added thumbnail with it on her bio page.

**Comment by sethrubenstein** [comment]
Hey @devansart this actually looks database driven. Those posts are rather old so for some reason dont have all the meta data they need. Quick solution is just go to any post thats not showing up in her byline and click update, just a quick refresh of the post will make it pop up in her author list.

**Comment by devansart** [comment]
@sethrubenstein Ok. We'll give it a go. Thanks.
