### ISSUE TITLE
Host stateface on equitablegrowth.org

### ISSUE THREAD

**Issue by austinclemens** [equitablegrowth/equitablegrowth.org#35]
We need to have this font hosted on our domain.

http://propublica.github.io/stateface/

**Comment by austinclemens** [comment]
[stateface-regular-webfont.eot | uploaded via ZenHub](https://files.zenhub.io/56210d08de40abbb4875dee5)

[stateface-regular-webfont.svg | uploaded via ZenHub](https://files.zenhub.io/56210d0fde40abbb4875dee6)

[stateface-regular-webfont.ttf | uploaded via ZenHub](https://files.zenhub.io/56210d11de40abbb4875dee7)

[stateface-regular-webfont.woff | uploaded via ZenHub](https://files.zenhub.io/56210d13de40abbb4875dee8)

**Comment by sethrubenstein** [comment]
http://equitablegrowth.org/wp-content/themes/sprout/bower_components/stateface/font/webfont/stateface-regular-webfont.eot

**Comment by austinclemens** [comment]
Thanks but I need at least the .woff and the .ttf hosted as well. I'm getting 404s on those right now. The .eot is just legacy IE support.

**Comment by sethrubenstein** [comment]
Hey @austinclemens sorry this release isnt out the door just yet. We'll let you know when it is and then youll be able to access all the fonts.

**Comment by sethrubenstein** [comment]
Hey @austinclemens these font files are now available.
