### ISSUE TITLE
Resizing the site on ipads

### ISSUE THREAD

**Issue by devansart** [equitablegrowth/equitablegrowth.org#36]
A user emailed me with a request: He'd like to be able to zoom into the site to be able to read more easily on his ipad. He mentioned this site allows him to do it: croakey.org. I had to compare our site with that site to understand what he was talking about. Sure enough when I use the pinch and widen touch actions I'm able to enlarge the site so I can more easily read text. (Although there then is a need to slide left a right like a typewriter to read across the entire column width) 

I think it might be worth adding that functionality but I'd prioritize this down the list. Thought I'd put the issue in so I didn't forget.

**Comment by sethrubenstein** [comment]
We can try this however this is actually considered bad implementation on
Croakey.org when a site doesnt restrict zooming bc it can break things. The
better solution is to offer better typography on mobile devices so that you
dont feel the need to zoom in to be able to read something.

On Fri, Oct 16, 2015 at 4:08 PM Dave <notifications@github.com> wrote:

> A user emailed me with a request: He'd like to be able to zoom into the
> site to be able to read more easily on his ipad. He mentioned this site
> allows him to do it: croakey.org. I had to compare our site with that
> site to understand what he was talking about. Sure enough when I use the
> pinch and widen touch actions I'm able to enlarge the site so I can more
> easily read text. (Although there then is a need to slide left a right like
> a typewriter to read across the entire column width)
>
> I think it might be worth adding that functionality but I'd prioritize
> this down the list. Thought I'd put the issue in so I didn't forget.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/equitablegrowth/equitablegrowth.org/issues/36>.
>
-- 

----

Sent from my mobile

Seth Rubenstein

**Comment by devansart** [comment]
Good point. PGM made it sound like they put thought into that. I personally don't think it's hard to read on my ipad. But I think this guys is a bit older. Like I said let's leave this at a low priority for now. Thanks for your explanation too.

**Comment by sethrubenstein** [comment]
Is this still a ticket @devansart ?

**Comment by devansart** [comment]
@sethrubenstein Let's close this out for now. Thanks
