### ISSUE TITLE
Email a friend box NOT invite a friend

### ISSUE THREAD

**Issue by devansart** [equitablegrowth/equitablegrowth.org#38]
The email a friend box off the story page functions and reads like an invite a friend to join the newsletter. This was a ticket in the CAP system but I haven't heard anything regarding it and since we are ALL departing CAP I figure it's best to add the issue here.

**Comment by sethrubenstein** [comment]
@devansart So the functionality here is to not signup for a newsletter but rather email a friend the content they're looking at currently?

**Comment by devansart** [comment]
@sethrubenstein Yes. I went to the site to double check that but noticed when you added the new share tools that button disappeared. But if I remember correctly we wanted the user to be able to send the article to a friend.
