### ISSUE TITLE
Editable tagline for Equitablog and About Page

### ISSUE THREAD

**Issue by devansart** [equitablegrowth/equitablegrowth.org#39]
This is another ticket that has been in the CAP system and I thought I should move it. We would like the tops of the Equitablog and the About page editable. The paragraph at the top of the Grants page is editable and we'd like to carry that over to these two pages. I've included a screen grab.
![screen shot 2015-10-20 at 1 09 45 pm](https://cloud.githubusercontent.com/assets/14931609/10615112/ec7c2402-772b-11e5-804b-1003b8e96aeb.png)
![screen shot 2015-10-20 at 1 10 01 pm](https://cloud.githubusercontent.com/assets/14931609/10615111/ec79095c-772b-11e5-939b-be8550043fa5.png)

**Comment by sethrubenstein** [comment]
All pages as part of the refactor now have editable masthead options.
