### ISSUE TITLE
Author bio pages should display latest posts 

### ISSUE THREAD

**Issue by bribroder** [equitablegrowth/equitablegrowth.org#4]
Author bio pages should display the author's most recent posts.  Correct mark-up is in place, but the author.php template should be coded to pull posts by person record (instead of by user record, as coded by PGM).

**Comment by sethrubenstein** [comment]
Latest 10 and then load more pagination.

**Comment by sethrubenstein** [comment]
Right now pagination is broken. We'll be fixing this in #18. For the meantime I've set this function to return 20 most recent posts so just know that we'll be adding the "load more" function back in a few sprints from now.

**Comment by devansart** [comment]
@sethrubenstein Took a look at the homepage and noticed Marshall Stienbaum's name is linked to his unstyled bio page. Are you aware that that is on the live site now? Want to turn it off until the page gets styled correctly?

**Comment by sethrubenstein** [comment]
Yea go ahead and turn that off, my bad accidentally turned that on last night.

**Comment by devansart** [comment]
This looks like it is working. Clarification: we will see up to 20 until item #18 gets addressed. Correct?

**Comment by sethrubenstein** [comment]
Correct.

On Wed, Oct 7, 2015 at 9:47 AM Dave <notifications@github.com> wrote:

> This looks like it is working. Clarification: we will see up to 20 until
> item #18
> <https://github.com/equitablegrowth/equitablegrowth.org/issues/18> gets
> addressed. Correct?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/equitablegrowth/equitablegrowth.org/issues/4#issuecomment-146200659>
> .
>
-- 

----

Sent from my mobile

Seth Rubenstein
