### ISSUE TITLE
About page "Our Staff" section should pull from persons

### ISSUE THREAD

**Issue by bribroder** [equitablegrowth/equitablegrowth.org#5]
PGM coded the about page to pull the EG staff list from WordPress users.  This should be converted to pull from person records.  Person data is already in place on the site--we just need to code the display loop in the templates/page-about.php file.

Once this is complete, the Custom User Profile Photo plugin can be deleted from the repo.

- [ ] Add job titles to each person on the staff page
- [ ] Ability to customize order? Or sort alphabetically by last name?

**Comment by devansart** [comment]
@sethrubenstein When I added a staff member to the about page I noticed it pulls the members entire bio. We only would like it to pull title and list it along with the staff member's name.

**Comment by sethrubenstein** [comment]
So do you want any of the contact info, bio pic thats also there? Or do you want me to just remove the bio part?

**Comment by devansart** [comment]
The About page should show pic, name and title. The Bios' are just too long to show out on the About page. Let people click on the staff member to get the full bio. Make sense?

**Comment by devansart** [comment]
@sethrubenstein Added a screen cap to the Slack channel.
