### ISSUE TITLE
Colon or special character breaking tweet function

### ISSUE THREAD

**Issue by devansart** [equitablegrowth/equitablegrowth.org#50]
When a title has a ":" in it, it breaks the tweet function on story pages. I'm not sure if there are other characters that do it too. Consider seeing if other characters break it.

**Comment by sethrubenstein** [comment]
@devansart I'm not encountering any bug on say this article http://equitablegrowth.org/must-read-paul-krugman-the-investment-accelerator-and-the-woes-of-the-world/ when using the Tweet button or the selection highlighter tweet button. Can you upload a screenshot showing the issue youre encountering?

**Comment by devansart** [comment]
@sethrubenstein sure. Here's a screen cap of this page http://equitablegrowth.org/john-maynard-keynes-getting-one-very-wrong-todays-history-of-economic-thought/
<img width="849" alt="screen shot 2015-11-11 at 2 27 20 pm" src="https://cloud.githubusercontent.com/assets/14931609/11100646/7a5ee51a-8880-11e5-9ebb-7454cf0a4845.png">

**Comment by devansart** [comment]
@sethrubenstein I went to the Equitablog page off the homepage and clicked on the post in my past comment to get there. Not sure if that has anything to do with the problem.

**Comment by sethrubenstein** [comment]
Ah it's not the : in the title its the ' Today's.
Let me see what I can do about resolving that.

**Comment by sethrubenstein** [comment]
This release thatll go out tomorrow https://github.com/equitablegrowth/equitablegrowth.org/pull/51 will fix this entirely. I have apostrophes working now. Turns out there was a way that PGM was passing titles into the twitter share that was pretty horrific so we've removed that in favor of a new method.
