### ISSUE TITLE
Terms of Use and Privacy pages

### ISSUE THREAD

**Issue by devansart** [equitablegrowth/equitablegrowth.org#57]
We need to build two new pages to prep for the transition from CAP. The terms of use and privacy pages are linked to in the email newsletter pop-up box. This location is fine but we should probably build them into the footer as well. 

https://www.americanprogress.org/about/c3-terms/
https://www.americanprogress.org/about/c3-privacy-policy/

Can we create new pages in the WP back end and then have you guys create links to them in a couple places on the site? (email newsletter pop-up window and the footer)

**Comment by sethrubenstein** [comment]
As part of the refactor I've just added a footer menu that contains the social icons but you can slot in terms/privacy whatever other pages you want.
