### ISSUE TITLE
Hook up Eloqua to our email newsletter subscription button

### ISSUE THREAD

**Issue by devansart** [equitablegrowth/equitablegrowth.org#59]
We need to collect new email newsletter subscribers that register with us in Eloqua rather than collect them in wordpress.

**Comment by sethrubenstein** [comment]
@devansart Please paste the form embed code for the eloqua form that signs up for your email newsletter.

**Comment by devansart** [comment]
@sethrubenstein Sorry for any inconveniences this may cause: I've discovered after submitting this ticket that we are moving to SalesForce Cloud Jan.1. So setting us up in Eloqua would be a stop gap for only 30 days. So there are two things here—1) We'll need to send the incoming email addresses into SalesForce Cloud rather than Eloqua. AND 2) Will there be a way for us to get to the email addresses that have come in since launching into SalesForce Cloud?

**Comment by sethrubenstein** [comment]
Ah this is actually better I think that you're using Salesforce. Our Gravity Forms plugin has an addon service where we can push data to Salesforce. This makes it easier for us and you to make more complex forms.

So for the time being how about we do this for the Refactor.
I'll create a new Gravity Form for email signup and well have that data live exclusively in WordPress for the time being and we can export as a CSV for you and then come January we can work on the sync to Salesforce?
