### ISSUE TITLE
Style cap-byline person taxonomy pages like author pages...

### ISSUE THREAD

**Issue by bribroder** [equitablegrowth/equitablegrowth.org#6]
Style the user detail pages, which is in related ticket WCEG-187
http://equitablegrowth.org/person/nbunker/
should look like
http://equitablegrowth.org/author/nbunker/

Should pull the user's actual posts, not default posts.  Also twitter handle is not being put on person detail page

person records need the full name with hyphen. Staff page should be linking to this url.
http://equitablegrowth.org/person/ed-paisley/

**Comment by sethrubenstein** [comment]
Pull in latest 10 posts and then do pagination.
