### ISSUE TITLE
Style caption and credits

### ISSUE THREAD

**Issue by devansart** [equitablegrowth/equitablegrowth.org#63]
We need the captions and credits styled for images on regular post pages and the report tool. This ticket existed for some time but I can't find it so I have added here. I refer to this in Issue #52 since it relates to the report tool as well.

![caption-bylines](https://cloud.githubusercontent.com/assets/14931609/11570166/d3cd17bc-99c3-11e5-8227-c1c13f52c10c.png)

**Comment by sethrubenstein** [comment]
I may be able to whip up a style for this to coincide with tonights release.

**Comment by devansart** [comment]
Thanks that would be excellent. Since it's style/css would it be a change site-wide? So it would be in both the post page and the report tool?

**Comment by sethrubenstein** [comment]
Correct.

On Fri, Dec 4, 2015, 12:03 PM Dave <notifications@github.com> wrote:

> Thanks that would be excellent. Since it's style/css would it be a change
> site-wide? So it would be in both the post page and the report tool?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/equitablegrowth/equitablegrowth.org/issues/63#issuecomment-162022572>
> .
>
-- 

----

Seth Rubenstein
