### ISSUE TITLE
Posts with category Working Papers should be hidden from the front page

### ISSUE THREAD

**Issue by austinclemens** [equitablegrowth/equitablegrowth.org#65]
If a post has the category Working Papers, it should *only* show up on the working papers page. It should be hidden from all the R&A category pages even if it is flagged as one of those categories and it should never show up on the front page.

**Comment by sethrubenstein** [comment]
So if a post has the category "working papers" and even if its meta-tagged with the research and analysis section it should what not show up on the home page but it should show up on the research and analysis page... correct?

**Comment by austinclemens** [comment]
my title is slightly misleading - it should not show up on R&A either. It should only show up specifically on the working papers page. Literally the only way to see it should be to pull down the R&A menu and choose working papers

**Comment by sethrubenstein** [comment]
So if I go to the R&A page and I click more posts which is showing all posts meta-tagged with the R&A section then those posts that are R&A and tagged working papers then they shouldn't show up on subsequent more posts pages?

**Comment by austinclemens** [comment]
Correct. They should be completely confined to http://equitablegrowth.org/category/working-papers/

I realize this is probably tied to the data restructuring - will it be possible to get this by mid-January?

**Comment by austinclemens** [comment]
They don't even need to remain R&A posts because they don't behave like other R&A posts - this could be accomplished with a totally new post type or whatever. The only relationship they have to R&A is that you get to the page via the R&A pulldown.

**Comment by sethrubenstein** [comment]
I'm not entirely sure this is doable the way you want by mid January. However, a simple solution is for your posts that are tagged working papers... just don't also tag R&A so the posts will appear in the working papers archive page but just have no relationship with R&A.

**Comment by austinclemens** [comment]
I'm not sure that will work - we have to choose one of three post types on the back end - R&A, equitablog, or data resource center. We don't want these to appear in any of those feeds, so none of those will work exactly right.

**Comment by austinclemens** [comment]
There's a distinction here between the post type and the post category. What we really want is a totally new post type I think. Posts of any type can be put in the 'human capital' category, but equitablog posts should only show up on the equitablog feed, and a 'working papers' post type should only show up in the working papers feed. Which is to say that the more I think about it, this is really tightly linked to #64

**Comment by sethrubenstein** [comment]
In the refactor launching tonight you don't have to select those. If you don't select that post type then the content will just live but wont appear on any of those post type pages unless you tell it to. So tagging a post in working papers but leaving out a post type that post will only appear in the working papers category archive.

**Comment by austinclemens** [comment]
Ah ok, that sounds like it will work

**Comment by austinclemens** [comment]
This does in fact work
