### ISSUE TITLE
Post-2.0 Release Tweaks/Fixes

### ISSUE THREAD

**Issue by sethrubenstein** [equitablegrowth/equitablegrowth.org#68]
- [x] "Uncategorized" label should not display.
- [x] Articles in the top slot on the homepage are not showing authors (eg the very first story on the homepage right now)
- [x] Reports are not showing authors in the body of the report (eg http://equitablegrowth.org/report/the-benefits-and-costs-of-investing-in-early-childhood-education/)
- [x] Articles that are flagged as wide-format appear to have lost that flag (eg http://equitablegrowth.org/state-page-MT/)
- [x] Reports seem to have changed how they display excerpts on the front page - eg 'A snapshot of the long-term impacts of universal prekindergarten' is showing the entire overview right now. I'm not sure if it was showing part of the overview before or what but it's much longer now.
- Need to implement character length restriction
- [x] A May 12th equitablog post is currently leading the equitablog feed on the front page only.
- [x] Not sure if this is a bug but on this page: http://equitablegrowth.org/about/#eg-steering-committee if you scroll down, the social tools overlay people's bios.
- [x] 'Advisory Board' and 'Our Staff' in the About menu seem to be improperly specified links
- [x] Footnote styling in reports has reverted to the old blue box style (http://equitablegrowth.org/report/equitable-growth-and-southern-californias-aerospace-industry/) instead of the green arrow style we had
- [x] lost the small equitable growth icon (small round line chart) It used to display to the left of About once you scrolled down. The styling of the dropdown menus has changed. It used to be a more delicate font rather than repeating the style.
- [x] Downloads on a post page now only show file type and not the file name. http://equitablegrowth.org/explaining-the-history-of-technology-series-and-equitable-growth/
- [x] Styling of subhead on report tool page is gray an not readable.
- [x] The value added icon does not show up on value added posts when the check box is checked.
- [x] Interactives placed in normal posts no longer go full bleed. Contrast the waffle chart on this page: http://equitablegrowth.org/state-page-WA/ which is in the well, with the full-bleed one on this report page: http://equitablegrowth.org/report/prek-snapshot-us/
- [x] The header titles on these pages http://equitablegrowth.org/grant-program/2014-grantees/ and http://equitablegrowth.org/grant-program/2015-grantees/ belong in the green area above the page content not in the content well. Like this: http://equitablegrowth.org/grant-program/
- [x] We used to have a header image on Equitablog. Similar to the green one on the about page. There was a tagline Equitablog—The conversation on inequality that Washington should be having. I tried to add it back but the featured post might be hiding it or conflicting with it somehow.

**Comment by austinclemens** [comment]
Articles in the top slot on the homepage are not showing authors (eg the very first story on the homepage right now)

Reports are not showing authors in the body of the report (eg http://equitablegrowth.org/report/the-benefits-and-costs-of-investing-in-early-childhood-education/)

Articles that are flagged as wide-format appear to have lost that flag (eg http://equitablegrowth.org/state-page-MT/)

Reports seem to have changed how they display excerpts on the front page - eg 'A snapshot of the long-term impacts of universal prekindergarten' is showing the entire overview right now. I'm not sure if it was showing part of the overview before or what but it's much longer now.

**Comment by austinclemens** [comment]
The featured image of the top equitablog post is missing from the front page (http://equitablegrowth.org/weekend-reading-34/)

**Comment by austinclemens** [comment]
A May 12th equitablog post is currently leading the equitablog feed.

**Comment by austinclemens** [comment]
Not sure if this is a bug but on this page: http://equitablegrowth.org/about/#eg-steering-committee if you scroll down, the social tools overlay people's bios.

**Comment by austinclemens** [comment]
'Advisory Board' and 'Our Staff' in the About menu seem to be improperly specified links

**Comment by austinclemens** [comment]
Footnote styling in reports has reverted to the old blue box style (http://equitablegrowth.org/report/equitable-growth-and-southern-californias-aerospace-industry/) instead of the green arrow style we had

**Comment by sethrubenstein** [comment]
Removing the filter sort ability item here as we have a ticket for this and espoused on it in the release notes. This functionality never worked from PGM so we pulled it to be rewritten entirely. Expect that to be added back in by end of week.

**Comment by devansart** [comment]
I see. I agree with you. Leave as is but remove the widget for those pages. Thanks.

**Comment by sethrubenstein** [comment]
@devansart on that last item you just need to add content to the Blurb and pick a masthead image. It'll work.

**Comment by sethrubenstein** [comment]
I've created #71 to facilitate the full bleed interactives on non report post types. This is one thats better to take some time to create a good solution rather than slap something half-broken up.
